### ISSUE TITLE
Cannot find pg_config executable when installing requirements.

### ISSUE THREAD

**Issue by clu5** [realpython/image-of-the-day#2]
`Collecting Django==1.9.5 (from -r requirements.txt (line 1))
  Using cached Django-1.9.5-py2.py3-none-any.whl
Collecting Pillow==3.2.0 (from -r requirements.txt (line 2))
  Using cached Pillow-3.2.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting psycopg2==2.6.1 (from -r requirements.txt (line 3))
  Using cached psycopg2-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

```
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6l/v90n_csd2vq8qpkfbymv61zm0000gn/T/pip-build-p1b60n08/psycopg2/`

**Comment by j1z0** [comment]
This error looks like it’s from an incorrect setup of postgres, please double check your postgres installation and follow the instructions there.  Most likely you don’t have your path setup correctly so the system can find the pg_config executable.
